# version: '3.7'
# services:
#   mysql-db:
#     container_name: mysql-db
#     image: mysql:latest
#     environment:
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_ROOT_HOST: "%"
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_ALLOW_EMPTY_PASSWORD: 1
#     ports:
#       - '3306:3306'
#     restart: always
#     env_file:
#       - ./.env
#     networks:
#       - backend
# networks:
#   backend:
#     driver: bridge

version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://user:password@database:3306/express
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: express
      MYSQL_USER: user
      MYSQL_PASSWORD: password
