version: "3.9"

services:
  server:
    build: 
     context: .
     dockerfile: Dockerfile
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db
    # env_file:
    #   - ./server/.env
    volumes:
     - ./server:/var/www
    expose:
      - "8080"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: express
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./server/public:/usr/share/nginx/html

volumes:
  dbdata:
