name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd server && npm install
      - name: Build project
        run: cd server && npm run build

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: cd server && npm install
  #     - name: Build project
  #       run: cd server && npm run build
  #     - name: Deploy to production
  #       run: cd server && npm run prod

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: Express-Prisma/my-express-app-image:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull Express-Prisma/my-express-app-image:latest
          docker rm -f your-container-name || true
          docker run -d --name your-container-name -p 3000:3000 Express-Prisma/my-express-app-image:latest
